// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSitesi.Data.Concrete.EfCore.Contexts;

#nullable disable

namespace YemekSitesi.Data.Migrations
{
    [DbContext(typeof(YemekSitesiContext))]
    partial class YemekSitesiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "98eb61c0-78fb-44b7-83ad-271f6499edae",
                            RoleId = "a075ac2b-3d93-4bc9-b257-bd400d06f05d"
                        },
                        new
                        {
                            UserId = "fde75564-20a9-4b48-9c12-eb97fffbd814",
                            RoleId = "d946c549-a82d-43ec-a1fd-0f2914fa46fd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sizler için özenle hazırlanmış Çorba Tariflerimiz burada bulunmaktadır",
                            Name = "Çorba",
                            Url = "corba"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sizler için özenle hazırlanmış Kurabiye Tariflerimiz burada bulunmaktadır",
                            Name = "Kurabiye",
                            Url = "kurabiye"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sizler için özenle hazırlanmış Tatlı Tariflerimiz burada bulunmaktadır",
                            Name = "Tatlı",
                            Url = "tatlı"
                        });
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Foods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = "25dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Öncelikle domatesler rendelenir. Ardından tereyağı ve sıvı yağ tencereye alınır, tereyağı eritilir.Tereyağı eridikten sonra un eklenerek biraz kavrulur. Unun kokusu çıktıktan sonra domates salçası eklenir ve biraz karıştırılarak kavrulurRendelenmiş domatesler eklenir. 3-4 dakika daha kavrulur. 4 su bardağı su eklenerek çırpılır, kısık ateşte pişmeye bırakılır. Dilerseniz bu aşamada veya servisten önce çorbayı blenderdan geçirerek pürüzsüz bir kıvam almasını sağlayabilirsiniz.Tuz ve süt eklenerek karıştırılır. Tuz miktarını kendi damak zevkinize göre ayarlayabilirsiniz. Hazır olan çorba ocaktan alınarak kaselere paylaştırılır. İsteğe göre üzerine kaşar peyniri rendesi ve karabiber serpilir.Nefis Sütlü domates çorbası tarifimiz servise hazır. Deneyeceklere afiyet olsun.",
                            ImageUrl = "corba1.png",
                            IsApproved = true,
                            IsHome = true,
                            Material = "2 yemek kaşığı sıvı yağ, 1 yemek kaşığı tereyağı, 2 tepeleme yemek kaşığı un, yemek kaşığı domates salçası, 5 adet domates, 4 su bardağı su, Yarım su bardağı süt, 1 silme tatlı kaşığı tuz",
                            Name = "Sütlü Domates Çorbası",
                            Url = "sütlü-domates-corbasi"
                        },
                        new
                        {
                            Id = 2,
                            CookingTime = "10dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ezogelin çorbası yapmak için düdüklü tencerede önce rendelemiş olduğumuz soğanı ve ezmiş olduğumuz sarımsağı tereyağında kavuruyoruz.Soğanlar diriliğini kaybetsin yeterli yakmadan orta ateşte kavuralım. Soğanlar kavrulunca naneyi, kırmızı biberi ve salçayı ilave edip. Kavurmaya devam edelim.Bir iki karıştırdıktan sonra yıkadığımız mercimeği, pirinci, bulguru ve tuzunu da ilave ederek karıştıralım.Başka bir tarafta kaynamakta olan 2 litreye yakın suyu üzerine boşaltalım.Düdüklünün kapağını ve düdüğünü kapattıktan sonra 10 dakika pişiriyoruz. Deneyeceklere afiyet olsun.",
                            ImageUrl = "corba2.png",
                            IsApproved = false,
                            IsHome = false,
                            Material = "1 su bardağı kırmızı mercimek, 1 tatlı kaşığı pirinç, 1 tatlı kaşığı bulgur, 2 çay kaşığı pul biber, 1 yemek kaşığı nane, 2 diş sarımsak, 1 orta boy soğan, 1 yemek kaşığı biber salçası, 1 yemek kaşığı tereyağı, 2 litreye yakın sıcak su, Tuz",
                            Name = "Ezogelin Çorbası",
                            Url = "ezogelin-corbasi"
                        },
                        new
                        {
                            Id = 3,
                            CookingTime = "15dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kırmızı mercimek çorbası için sıvı yağı tencereye alınarak yemeklik doğranan soğanlar hafif pembeleşinceye kadar kavrulur.Daha sonra un ilave edilerek kısık ateşte kavurmaya devam edilir. Salça kullanılacak ise salça ilave edilir, kavrulduktan sonra küp küp doğranmış havuç ve iyice yıkanıp suyu süzülen mercimekler ilave edilir.Üzerine su eklenerek karıştırılır ve tencerenin kapağı kapatılır. Çorba piştikten sonra el blenderı ile güzelce ezilir.Karabiber, tuz ve isteğe bağlı olarak kimyon eklenir ve karıştırılır. 5 dakika daha pişirelerek ocaktan alınır.Bu arada küçük bir tavaya iki yemek kaşığı tereyağı alınır, kızdırılır ve bir tatlı kaşığı kırmızı toz biber eklenerek ocaktan alınırBir dilim limon ile servis edilir. Deneyeceklere afiyet olsun",
                            ImageUrl = "corba3.png",
                            IsApproved = true,
                            IsHome = false,
                            Material = "2 su bardağı kırmızı mercimek, 1 adet soğan, 2 yemek kaşığı un, 1 adet havuç, 1 tatlı kaşığı tuz, Yarım çay kaşığı karabiber, 1 çay kaşığı kimyon (isteğe bağlı), 2 litre sıcak su, 5 yemek kaşığı sıvı yağ",
                            Name = "Kırmızı Mercimek Çorbası",
                            Url = "kirmizi-mercimek-corbasi"
                        },
                        new
                        {
                            Id = 4,
                            CookingTime = "30dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Öncelikle tenceremize yoğurt, un ve suyu ilave ederek tel çırpıcı yardımı ile pürüzsüz bir kıvam alana kadar çırpalım.Çorbamız kaynadıktan sonra erişteyi ekleyelim ve kısık ateşte ara ara karıştırarak şehriyeler yumuşayıncaya kadar pişirelim.Tuzumuzu da ekleyelim ve 1-2 dakika daha kaynatarak ocağı kapatalım. Çorbamızı 10 dakika kadar dinlenmeye bırakalım.Sosu için uygun bir sos tavasına tereyağını alalım ve eritelim.Üzerine pul biber ve naneyi ekleyerek kızdıralım ve ocaktan alalım.Çorbamızı kaselere alalım ve üzerine sostan gezdirerek servis edelim. ",
                            ImageUrl = "corba4.png",
                            IsApproved = false,
                            IsHome = false,
                            Material = "1 su bardağı yoğurt, 3 tepeleme yemek kaşığı un, 5 su bardağı su, 1 çay bardağı erişte, 1 silme tatlı kaşığı tuz, 1 yemek kaşığı tereyağı, 1 tatlı kaşığı kırmızı toz biber, 1 tatlı kaşığı nane",
                            Name = "Yoğurt Çorbası",
                            Url = "yogurt-corbasi"
                        },
                        new
                        {
                            Id = 5,
                            CookingTime = "20dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brokoliyi, küp küp doğradığınız patatesi, halka halka dilimlenmiş havucu ve doğradığınız soğan bir tencereye koyun.Üzerini geçecek kadar su ilave ederek sebzeler yumuşayana kadar haşlayın. Başka bir tencerede tereyağını eritin ve unu ekleyerek kavurun.Üzerine yavaş yavaş sütü ilave ederek karıştırarak beşamel sosu pişirin. Sebzeleri beşamel sosun üzerine ilave ederek haşlama suyunun da yarısı kadarını tencereye alarak blender ile güzelce ezin.Tuz ve karabiberi ekleyerek 3-4 dakika kadar kaynatın.Son olarak çorbanın süt kremasını ilave edin ve 1-2 taşım kaynattıktan sonra çorbayı ateşten alabilirsiniz. Afiyet olsun.",
                            ImageUrl = "corba5.png",
                            IsApproved = false,
                            IsHome = false,
                            Material = "500 g brokoli, 1 adet havuç, 1 adet orta boy patates, 1 adet soğan, Sıcak su (üzerini geçecek kadar), 2 su bardağı süt, 1 çay bardağı süt kreması, 2 yemek kaşığı tereyağ, 1 yemek kaşığı un, Tuz, Karabiber",
                            Name = "Brokoli Çorbası",
                            Url = "brokoli-corbasi"
                        },
                        new
                        {
                            Id = 6,
                            CookingTime = "15dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İlk olarak sıvı yağ ve tereyağı karıştırılır. Sonra diğer malzemeler eklenir karıştırılır. En son un eklenip kulak memesi kıvamında hamur elde ediyoruz, fazla yumuşakolmasın hamur çünkü kurabiyelerimiz dağılabilir.Resimdeki gibi yada istediğiniz gibi şekil verip üstüne yumurta sarısı sürüp susam, çörek otu serpin. Bu malzemelerden iki tepsi kurabiye çıkmaktadır Afiyet olsun.",
                            ImageUrl = "kurabiye1.png",
                            IsApproved = true,
                            IsHome = true,
                            Material = "250 gram margarin veya tereyağı, 2 yemek kaşığı sıvı yağ, 2 yemek kaşığı toz şeker, 2 yemek kaşığı sirke, 1 paket kabartma tozu, 1 tatlı kaşığı tuz, Aldığı kadar un,1 yumurta sarısı, Susam ve çörekotu",
                            Name = "Tuzlu Kurabiye",
                            Url = "tuzlu-kurabiye"
                        },
                        new
                        {
                            Id = 7,
                            CookingTime = "20dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Margarin yada tereyağı, sıvı yağ ve pudra şekerinin 1 su bardağını yoğuruyoruz. Kalan yarım bardaklık pudra şekeri üzeri için kullanılacak5 dk. yoğurduktan sonra nişasta ve unu ilave ediyoruz. İyice yoğuracağız çünkü hamur parçalanacaktırŞekil verirken 2 adet ceviz büyüklüğünde bir parça koparıp rulo şekline getirin. Sağ, sol ve üst kısmına çatalla şekil verip yan yan kesinTepsiyi yağlamayın hamur zaten yağlı. Kurabiyeleri tepsiye dizinÖnceden ısıtılmış fakat ılık olmalı 160 derecelik fırında 15 dk. pişirin. Deneyeceklere afiyet olsun",
                            ImageUrl = "kurabiye2.png",
                            IsApproved = false,
                            IsHome = true,
                            Material = "1 paket tereyağı ya da margarin, 1 kahve fincanı sıvı yağ, 4 çorba kaşığı buğday nişastası, 1 su bardağı pudra şekeri, Aldığı kadar un",
                            Name = "Un Kurabiyesi",
                            Url = "un-kurabiyesi"
                        },
                        new
                        {
                            Id = 8,
                            CookingTime = "25dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İlk olarak yoğurma kabına oda sıcaklığındaki tereyağı, pudra şekeri, yumurta sarısını alarak yoğuralım.Daha sonra un ve kabartma tozu ilave edip kulak memesi kıvamına gelecek şekilde yoğuruyoruz. Ayrı bir kabın içerisine fındık kırığı ile şekeri karıştıralım.Hamurdan parçalar kopartarak yuvarlayıp önce yumurta akına batırıp kırılmış fındık ve şeker karışımına bulayalım.180 derece fırında hafif kızarıncaya kadar yaklaşık 25 dakika pişiriyoruz. Afiyet olsun.",
                            ImageUrl = "kurabiye3.png",
                            IsApproved = false,
                            IsHome = true,
                            Material = "250 gram tereyağı, 1 su bardağı pudra şekeri, 1 yumurta sarısı (akı üzerine), 1 paket kabartma tozu, Aldığı kadar un, 1 çay bardağı fındık kırığı, 1 yemek kaşığı toz şeker, Yumurta akı",
                            Name = "5 Dakika Kurabiyesi",
                            Url = "5-dakika-kurabiyesi"
                        },
                        new
                        {
                            Id = 9,
                            CookingTime = "25dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tereyağı nın Üzerine pudra şekeri, sıvı yağ, yumurta akı, vanilya, kabartma tozu, tarçın ve unun bir kısmını alarak yoğuralım. Unu yavaş yavaş ilave ederek ele yapışmayan yumuşak kıvamlı bir hamur elde edelim.Hamurumuz istediğimiz kıvama geldikten sonra cevizi de ekleyelim ve son kez yoğuralım.Tüm hamurumuz bitene kadar şekillendirelim. Kurabiyelerimizi önceden ısıttığımız 160 derece fırında yaklaşık 25 dakika pişmeye bırakalım. Afiyet Olsun",
                            ImageUrl = "kurabiye4.png",
                            IsApproved = false,
                            IsHome = true,
                            Material = "250 gr margarin veya tereyağı, Yarım çay bardağı sıvı yağ, 1 çay bardağı pudra şekeri, 1 adet yumurta akı, 1 çay bardağı ince dövülmüş ceviz, 1 çay kaşığı tepeleme dolu tarçın, 1 paket vanilya, 1 paket kabartma tozu,4,5-5 su bardağı un",
                            Name = "Tarçınlı Cevizli Kurabiye",
                            Url = "tarcinli-cevizli-kurabiye"
                        },
                        new
                        {
                            Id = 10,
                            CookingTime = "15dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oda ısısında yumuşamış margarini ve pudra şekerini iyice karıştıralım. Yumurtayı ekleyip karıştıralım.Un, kabartma tozu ve vanilyayı eleyerek ilave edip yoğuralım. En son damla çikolatayı ekleyip yoğuralım.Önceden ısıtılmış fırında 180 derecede yaklaşık 10-15 dakika kadar pişirelim. Soğuyunca servis yapalım.",
                            ImageUrl = "kurabiye5.png",
                            IsApproved = true,
                            IsHome = true,
                            Material = "100 gram tereyağı veya margarin, 1 adet yumurta, 1 su bardağı damla çikolata, 1 su bardağı pudra şekeri, 2,5 su bardağı un, 1 paket vanilya, 1 paket kabartma tozu",
                            Name = "Damla Çikolatalı Kurabiye",
                            Url = "damla-cikolatali-kurabiye"
                        },
                        new
                        {
                            Id = 11,
                            CookingTime = "30dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pirinçleri güzelce yıkadıktan sonra 2 su bardağı su ile pişene kadar haşlayın.Haşlanan pirinçlerin üzerine sütü, vanilyayı ilave edip kaynatınKarışım kaynamaya başlayınca şekeri ve yarım su bardağı sütle karıştırdığınız 3 yemek kaşığı buğday nişastasını ilave ediniz.10 - 15 dk.daha kaynatıp altını kapatın. . Fırın için uygun ısıya dayanıklı sütlaç kaselerine sütlaçlarınızı paylaştırın.Tepsinize soğuk su doldurun ve sütlaç kaplarını fırın tepsinize dizin. Tepsiyi fırınınızın en üst rafına yerleştirin.180 derecede, sütlaçlarınız kızarana kadar fırınlayın. Afiyet olsun.",
                            ImageUrl = "tatlı1.png",
                            IsApproved = false,
                            IsHome = true,
                            Material = "1 litre süt,  1 su bardağı şeker,  Yarım su bardağı pirinç,  3 yemek kaşığı buğday nişastası,  1 paket vanilya, 2 su bardağı su, yarım su bardağı süt",
                            Name = "Fırında Sütlaç",
                            Url = "firinda-sütlaç"
                        },
                        new
                        {
                            Id = 12,
                            CookingTime = "13dk",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yumurta ve şekeri el çırpıcısı ile çırpıyoruz.Üzerine diğer malzemeleri ekleyip kek kıvamını elde ediyoruz. Sufle kaplarına döküp üzerine parça çikolata koyuyoruz.Tencerenin içine kaynar suyu döküyoruz.İçine sufleleri koyup kapağını kapatıyoruz.Yaklaşık 7 - 8 dakika pişiriyoruz. Afiyet şeker olsun ",
                            ImageUrl = "tatlı2.png",
                            IsApproved = true,
                            IsHome = true,
                            Material = "1 adet yumurta, Yarım çay bardağı şeker, Yarım çay bardağı sıvı yağ, Yarım çay bardağı süt, 2,5 3 yemek kaşığı un, 1 yemek kaşığı kakao, 1 paket vanilya, 1 çay kaşığı kabartma tozu,2 parça çikolata",
                            Name = "Sufle",
                            Url = "sufle"
                        });
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.FoodCategory", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodCategory", (string)null);

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            FoodId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            FoodId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            FoodId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            FoodId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            FoodId = 12,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a075ac2b-3d93-4bc9-b257-bd400d06f05d",
                            Description = "Admin Rolü",
                            Name = "Admin",
                            NormalizedName = "ADMİN"
                        },
                        new
                        {
                            Id = "d946c549-a82d-43ec-a1fd-0f2914fa46fd",
                            Description = "User Rolü",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "98eb61c0-78fb-44b7-83ad-271f6499edae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d152303-ec6b-4247-9a61-c915a814a500",
                            DateOfBirth = new DateTime(1980, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sümeyye",
                            Gender = "Kadın",
                            LastName = "Yüce",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFWjsGJuDORTcjtl3dz3SIOL+7srC7I47+cY55QHvaPAdlBKwz+RG8NO1aZ2yhEr2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "000c3be7-8692-4b84-b7f4-8f2c5b2a44a8",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "fde75564-20a9-4b48-9c12-eb97fffbd814",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d001b10-21cd-414e-9074-577c2ada1216",
                            DateOfBirth = new DateTime(1986, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ornek",
                            Gender = "Erkek",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEIBZdP2wZ+DPx62AQFP7P0UlKeCAGrnQKGiOPr7ca/nv8+DjLvlHPSRuftghPJWu4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6ae208e-18ce-447e-8481-fcf8298e100a",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("YemekSitesi.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YemekSitesi.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YemekSitesi.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("YemekSitesi.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSitesi.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YemekSitesi.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.FoodCategory", b =>
                {
                    b.HasOne("YemekSitesi.Entity.Concrete.Category", "Category")
                        .WithMany("FoodCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSitesi.Entity.Concrete.Food", "Food")
                        .WithMany("FoodCategories")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.Category", b =>
                {
                    b.Navigation("FoodCategories");
                });

            modelBuilder.Entity("YemekSitesi.Entity.Concrete.Food", b =>
                {
                    b.Navigation("FoodCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
